/*

Start Date: March 8th 2020 - 12:50 am
Finish Date: March 8th 2020 - 1:03 am

Description: 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Notes: I'm impressed that I solved the problem recursively. I could have done it faster if I remembered to add the original 2 into the sum 
because it is also an even fibonacci number that should be in the sum.
*/

function evenFibonacci(first, second)
{
    var newFib = first + second;

    if (newFib > 4000000)
    {
        return 0
    }
    else
    {
        if (newFib % 2 == 0)
        {
            return evenFibonacci(second, newFib) + newFib;
        }
        else
        {
            return evenFibonacci(second, newFib);
        }
    }
}

console.log(evenFibonacci(0, 1));

